---
config:
  theme: redux
  fontFamily: '"JetBrainsMono", "monospace"'
  displayMode: compact
  flowchart:
    htmlLabels: true
    curve: 'basis'
---
flowchart LR
    ReadTrace(Read trace) --> ReqValid{Request is Valid}

    ReqValid -- NO --> END
    ReqValid -- YES --> ExistInDram{Exist in DRAM}

    ExistInDram -- YES --> DRAMHit(DRAM Hit)

    ExistInDram -- NO --> DRAMMiss(DRAM Miss) --> InsertToDram(Insert To DRAM)
    DRAMMiss -->ExistInFlash{Exist in Flash}

    ExistInFlash -- NO --> FlashMiss(Flash Miss)
    ExistInFlash -- YES --> FlashHit(Flash Hit)

    InsertToDram --> DramHasSpace{DRAM Has Enough Space}
    DramHasSpace -- YES --> InsertMetadataDRAM(Insert to DRAM Metadata Table)
    DramHasSpace -- NO --> EvictFromDram(Evict From DRAM)

    OnEviction2 --> EvictedObjFreqMtN{Evicted Object Freq > N}
    EvictFromDram --> OnEviction1(On Eviction)
    EvictFromDram -- YES --> DramHasSpace

    OnEviction2(On Eviction)
    EvictedObjFreqMtN -- YES --> FlashHasSpace

    FlashHasSpace{Flash Has Enough Space}
    FlashHasSpace -- YES --> InsertToFlash(Insert To Flash)
    FlashHasSpace -- NO --> EvictFromFlash(Evict From Flash) --> FlashHasSpace
